name: CD Development

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: development

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Trigger Render Deployment
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_DEV_URL }}

      - name: Deployment Confirmation
        run: |
          echo "Deployment to development triggered at $(date)"